### ISSUE TITLE
Firebase Hosting

### ISSUE THREAD

**Issue by tokku5552** [tokku5552/flutter_liff_scheduler#6]
- Firebase Hosting
    - Firebase PJとリポジトリを紐づける
    - デプロイはGitHub Actionsに載せておく

**Comment by tsukamoto1783** [comment]
@tokku5552 

↓こんぶさんの記事の手順をベースに、デプロイしたらいいでしょうか？？
https://zenn.dev/pressedkonbu/articles/deploy-flutter-web-app-with-firebase-hosting

**Comment by tokku5552** [comment]
そうですね！こんな感じでお願いします 👍

**Comment by tokku5552** [comment]
テスト

**Comment by tokku5552** [comment]
@matttake 
返信遅くなりすみません 🙇‍♂️ 
そうですね！こんな感じでお願いします 👍
