### ISSUE TITLE
liffの作成とflutter webへの紐づけ(liff.init()の実施くらいまで)

### ISSUE THREAD

**Issue by tokku5552** [tokku5552/flutter_liff_scheduler#8]
- liffの作成とflutter webへの紐づけ(liff.init()の実施くらいまで)

**Comment by tsukamoto1783** [comment]
## 進め方
[pub.dev: js ](https://pub.dev/packages/js)使ってinit()まで実施しようかと考えてます。
  
以下記事とかを参考に、動作確認しながら実装しようかと思ってます。
[参考記事①](https://tech.pscsrv.co.jp/2020/04/02/js%E3%81%AE%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%82%92%E7%B0%A1%E5%8D%98%E3%81%ABdart%E3%81%8B%E3%82%89%E4%BD%BF%E3%81%86%E6%96%B9%E6%B3%95/)  
[参考記事②](https://flutter-square.com/js-call-dart/)  
  
## 備考
※土日予定あるので、水曜にはPR出せるまで持っていきたい目標でやってみます。  
→init()が実装できてなくて、後工程に響くようなら、こちらのIssueのAssigneesぶんどってもらっても全然大丈夫です🙇‍♂️

**Comment by tsukamoto1783** [comment]
@tokku5552 
@shinichi-arata 

## 進捗
jsパッケージを使用してのinit()が実装できておりません。  
色々と調べて試してみましたが上手くいかず、今日中にできそうにありません。。🙇‍♂️  

※自作のJavaScript関数は、jsパッケージを使用して呼び出せる事の動作確認はできました。
  ですが、LineSDK内の関数を呼び出し方が分からず詰まっております。

## ご提案
### 案①
荒田さんは、jsパッケージを使用したinit()の実装って以前にできておりますでしょうか？  
もしinit()の実装したことある(すぐに再現可能)ならば、代わりにこのIssueを担当してもらうことは可能でしょうか？  

### 案②
案①が無理な場合、 一旦は動く事を優先して、[flutter_line_liff](https://pub.dev/packages/flutter_line_liff)パッケージを使用してのinit()でもよいでしょうか？  

※MTGで上記パッケージは使用しない。となりましたが、木曜までに一旦動くものを作る。という暫定処置として。
※上記パッケージを使用する場合は、以下の数行だけでinit()可能なことは確認済みです。
```
import 'package:flutter_line_liff/flutter_line_liff.dart';

Future<void> main() async {
  await FlutterLineLiff().init(
    config: Config(liffId:'LIFF_ID'),
  )

```

**Comment by shinichi-arata** [comment]
ごめんさい。その後の経過を書いていませんでした。すでにflutter_line_liffパッケージを利用中です。ご心配かけました。

**Comment by tsukamoto1783** [comment]
こちらのIsuueは、先日のMTGでClose(中断)となりましたが、調査できたところまで(詰まっていたところまで)記載いたします。(少しでもご参考になる箇所があれば幸いです🙇‍♂️)


# 詰まっていた内容
- jsパッケージを使用してinit()を呼び出し、ログイン画面を表示させることはできました。
以下コード参照。
<p>
<img src="https://user-images.githubusercontent.com/61080605/193430463-f1354cfe-8200-4630-bebd-b4e3bb4c801b.png" width="250" heigth="630">
</p>

```yaml
// 使用したフォルダ構成
project(root)
├─ lib
│  ├─ main.dart
│  └─ liff_init_call.dart
│    
└─ web
    ├─ index.html
    └─ liff_init.js
```

```dart
// main.dart
Future<void> main() async {
  await dotenv.load(fileName: "env");
  // init()をコール
  init(dotenv.env['LIFFID_KEY'].toString());
  // 上記init()がawait で呼び出せてないので、動作確認時は手動で時間空けてます。
  await Future.delayed(const Duration(seconds: 2));
```

```dart
// liff_init_call.dart
@JS()
library js_func;
import 'package:js/js.dart';

@JS('init')
external init(String liff_if);
```

```html
// index.html
// 記載省略
  <script src="flutter.js" defer></script>
  <!-- 差し込み -->
  <script  charset="utf-8"  src="https://static.line-scdn.net/liff/edge/versions/2.20.3/sdk.js"></script>
  <script src="liff_init.js" defer></script>
</head>
```

```js
// liff_init.js
function init(liff_if){
    liff.init({
        liffId: liff_if, // Use own liffId
        // 以下を有効にすれば、liff.login()メソッドが自動で実行。
        withLoginOnExternalBrowser: true, // Enable automatic login process
    });
}
```
&nbsp;
&nbsp;

ログイン画面表示できたしinit()完了か。と思っていましたが、確認でgetDecodedIDToken()を実行してユーザ情報を取得してみると、nullで情報を取得できない。  
→ユーザ情報が取得できない。ということはinit()もできていない？  
→上記を色々と試して、getDecodedIDToken()で値を取得できるように試みているところで詰まっていた状況です。  
→※上記の動作確認は自分のアカウントで作ったLiffをデプロイして確認しておりました。 
&nbsp;
 
```js
// liff_init.js
function init(liff_if){
    liff.init({
        liffId: liff_if, // Use own liffId
        // 以下を有効にすれば、liff.login()メソッドが自動で実行。
        withLoginOnExternalBrowser: true, // Enable automatic login process
    })
        .then(() => {
           // init()後にユーザ情報を取得 → consoleではnullで値が取得されない。。。
            const idToken = liff.getDecodedIDToken();
            console.log("idToken:"); // print decoded idToken object
        })
        .catch((err) => {
            console.log(err);
        });
}
```

**Comment by tokku5552** [comment]
@matttake 
記載ありがとうございます！

> 確認でgetDecodedIDToken()を実行してユーザ情報を取得してみると、nullで情報を取得できない。

これはもしかしたらFlutterではなくLINE側の仕様かもしれません 🤔 
この前のMTGでも少しお話しましたが、LINEは仕様上公開されていない開発中のLINEログインチャネルは、テスター以上のメンバー登録がされていないと、LINEログインが失敗するようになっています。また、ちょっとこのタスクはsdkではなくてjsでliff.initするというところに目標を置き直して継続しても良いかもですね 🤔

**Comment by heyhey1028** [comment]
@matttake 
情報共有ありがとうございます！
ゆーとさんのを参考にしたコードを「ngrokで解放」→「liffアプリのエンドポイントに設定」を行って確認した所、lineグループ内で立ち上げたLIFFではprofileやtokenなど取得する事ができました。なのでtokkuさんおっしゃる通り、LINEの仕様かと思いました！

**Comment by heyhey1028** [comment]
@tokku5552 
@shinichi-arata 
@matttake 

#29 
上記やり取りを参考にjsパッケージを使ったliff sdk呼び出しのサンプル作ってみました。

~~liffにアクセスする権限がないのか立ち上げられず、本プロジェクトで実際に試せてないですが、自分のプロジェクトでは動作したので行けるはず~~

行けてそう
<img width="900" alt="スクリーンショット 2022-10-03 17 12 32" src="https://user-images.githubusercontent.com/44666053/193530959-bb50bc63-e920-4bd6-846f-5e1aaa9eaa76.png">
